// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#include "Enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Enum_2eproto[7];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Enum_2eproto = nullptr;
const uint32_t TableStruct_Enum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nEnum.proto\022\010Protocol*w\n\023CREATE_PLAYER_"
  "ERROR\022\024\n\020CREATE_USER_NONE\020\000\022\024\n\020CREATE_US"
  "ER_FAIL\020\001\022\027\n\023CREATE_USER_SUCCESS\020\002\022\033\n\027CR"
  "EATE_USER_DUPLICATION\020\003*\266\001\n\013LOGIN_ERROR\022"
  "\016\n\nLOGIN_NUNE\020\000\022\017\n\013LOGIN_FAILE\020\001\022\021\n\rLOGI"
  "N_ID_NONE\020\002\022\021\n\rLOGIN_PW_NONE\020\003\022\026\n\022LOGIN_"
  "CREATE_FAILE\020\004\022\034\n\030LOGIN_CREATE_HAS_ACCOU"
  "NT\020\005\022\027\n\023LOGIN_ALREADY_LOGIN\020\006\022\021\n\rLOGIN_S"
  "UCCESS\020\007*E\n\014LOGOUT_ERROR\022\017\n\013LOGOUT_NUNE\020"
  "\000\022\020\n\014LOGOUT_FAILE\020\001\022\022\n\016LOGOUT_SUCCESS\020\006*"
  "i\n\nCHAT_ERROR\022\023\n\017CHAT_ERROR_NONE\020\000\022\023\n\017CH"
  "AT_ERROR_FAIL\020\001\022\031\n\025CHAT_ERROR_NOT_TARGET"
  "\020\002\022\026\n\022CHAT_ERROR_SUCCESS\020\003*=\n\nCHAT_STATE"
  "\022\014\n\010CHAT_ALL\020\000\022\017\n\013CHAT_NORMAL\020\001\022\020\n\014CHAT_"
  "WHISPER\020\002*T\n\020ENTER_ROOM_ERROR\022\023\n\017ENTER_R"
  "OOM_NONE\020\000\022\023\n\017ENTER_ROOM_FAIL\020\001\022\026\n\022ENTER"
  "_ROOM_SUCCESS\020\002*P\n\017EXIT_ROOM_ERROR\022\022\n\016EX"
  "IT_ROOM_NONE\020\000\022\022\n\016EXIT_ROOM_FAIL\020\001\022\025\n\021EX"
  "IT_ROOM_SUCCESS\020\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Enum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Enum_2eproto = {
    false, false, 745, descriptor_table_protodef_Enum_2eproto,
    "Enum.proto",
    &descriptor_table_Enum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_Enum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_Enum_2eproto,
    file_level_service_descriptors_Enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Enum_2eproto_getter() {
  return &descriptor_table_Enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Enum_2eproto(&descriptor_table_Enum_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CREATE_PLAYER_ERROR_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[0];
}
bool CREATE_PLAYER_ERROR_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LOGIN_ERROR_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[1];
}
bool LOGIN_ERROR_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LOGOUT_ERROR_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[2];
}
bool LOGOUT_ERROR_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CHAT_ERROR_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[3];
}
bool CHAT_ERROR_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CHAT_STATE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[4];
}
bool CHAT_STATE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ENTER_ROOM_ERROR_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[5];
}
bool ENTER_ROOM_ERROR_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EXIT_ROOM_ERROR_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[6];
}
bool EXIT_ROOM_ERROR_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
