// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum CREATE_PLAYER_ERROR : int {
  CREATE_USER_NONE = 0,
  CREATE_USER_FAIL = 1,
  CREATE_USER_SUCCESS = 2,
  CREATE_USER_DUPLICATION = 3,
  CREATE_PLAYER_ERROR_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CREATE_PLAYER_ERROR_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CREATE_PLAYER_ERROR_IsValid(int value);
constexpr CREATE_PLAYER_ERROR CREATE_PLAYER_ERROR_MIN = CREATE_USER_NONE;
constexpr CREATE_PLAYER_ERROR CREATE_PLAYER_ERROR_MAX = CREATE_USER_DUPLICATION;
constexpr int CREATE_PLAYER_ERROR_ARRAYSIZE = CREATE_PLAYER_ERROR_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CREATE_PLAYER_ERROR_descriptor();
template<typename T>
inline const std::string& CREATE_PLAYER_ERROR_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CREATE_PLAYER_ERROR>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CREATE_PLAYER_ERROR_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CREATE_PLAYER_ERROR_descriptor(), enum_t_value);
}
inline bool CREATE_PLAYER_ERROR_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CREATE_PLAYER_ERROR* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CREATE_PLAYER_ERROR>(
    CREATE_PLAYER_ERROR_descriptor(), name, value);
}
enum LOGIN_ERROR : int {
  LOGIN_NUNE = 0,
  LOGIN_FAILE = 1,
  LOGIN_ID_NONE = 2,
  LOGIN_PW_NONE = 3,
  LOGIN_CREATE_FAILE = 4,
  LOGIN_CREATE_HAS_ACCOUNT = 5,
  LOGIN_ALREADY_LOGIN = 6,
  LOGIN_SUCCESS = 7,
  LOGIN_ERROR_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LOGIN_ERROR_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LOGIN_ERROR_IsValid(int value);
constexpr LOGIN_ERROR LOGIN_ERROR_MIN = LOGIN_NUNE;
constexpr LOGIN_ERROR LOGIN_ERROR_MAX = LOGIN_SUCCESS;
constexpr int LOGIN_ERROR_ARRAYSIZE = LOGIN_ERROR_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LOGIN_ERROR_descriptor();
template<typename T>
inline const std::string& LOGIN_ERROR_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LOGIN_ERROR>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LOGIN_ERROR_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LOGIN_ERROR_descriptor(), enum_t_value);
}
inline bool LOGIN_ERROR_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LOGIN_ERROR* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LOGIN_ERROR>(
    LOGIN_ERROR_descriptor(), name, value);
}
enum LOGOUT_ERROR : int {
  LOGOUT_NUNE = 0,
  LOGOUT_FAILE = 1,
  LOGOUT_SUCCESS = 6,
  LOGOUT_ERROR_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LOGOUT_ERROR_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LOGOUT_ERROR_IsValid(int value);
constexpr LOGOUT_ERROR LOGOUT_ERROR_MIN = LOGOUT_NUNE;
constexpr LOGOUT_ERROR LOGOUT_ERROR_MAX = LOGOUT_SUCCESS;
constexpr int LOGOUT_ERROR_ARRAYSIZE = LOGOUT_ERROR_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LOGOUT_ERROR_descriptor();
template<typename T>
inline const std::string& LOGOUT_ERROR_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LOGOUT_ERROR>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LOGOUT_ERROR_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LOGOUT_ERROR_descriptor(), enum_t_value);
}
inline bool LOGOUT_ERROR_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LOGOUT_ERROR* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LOGOUT_ERROR>(
    LOGOUT_ERROR_descriptor(), name, value);
}
enum CHAT_ERROR : int {
  CHAT_ERROR_NONE = 0,
  CHAT_ERROR_FAIL = 1,
  CHAT_ERROR_NOT_TARGET = 2,
  CHAT_ERROR_SUCCESS = 3,
  CHAT_ERROR_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CHAT_ERROR_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CHAT_ERROR_IsValid(int value);
constexpr CHAT_ERROR CHAT_ERROR_MIN = CHAT_ERROR_NONE;
constexpr CHAT_ERROR CHAT_ERROR_MAX = CHAT_ERROR_SUCCESS;
constexpr int CHAT_ERROR_ARRAYSIZE = CHAT_ERROR_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CHAT_ERROR_descriptor();
template<typename T>
inline const std::string& CHAT_ERROR_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CHAT_ERROR>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CHAT_ERROR_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CHAT_ERROR_descriptor(), enum_t_value);
}
inline bool CHAT_ERROR_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CHAT_ERROR* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CHAT_ERROR>(
    CHAT_ERROR_descriptor(), name, value);
}
enum CHAT_STATE : int {
  CHAT_ALL = 0,
  CHAT_NORMAL = 1,
  CHAT_WHISPER = 2,
  CHAT_STATE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CHAT_STATE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CHAT_STATE_IsValid(int value);
constexpr CHAT_STATE CHAT_STATE_MIN = CHAT_ALL;
constexpr CHAT_STATE CHAT_STATE_MAX = CHAT_WHISPER;
constexpr int CHAT_STATE_ARRAYSIZE = CHAT_STATE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CHAT_STATE_descriptor();
template<typename T>
inline const std::string& CHAT_STATE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CHAT_STATE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CHAT_STATE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CHAT_STATE_descriptor(), enum_t_value);
}
inline bool CHAT_STATE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CHAT_STATE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CHAT_STATE>(
    CHAT_STATE_descriptor(), name, value);
}
enum ENTER_ROOM_ERROR : int {
  ENTER_ROOM_NONE = 0,
  ENTER_ROOM_FAIL = 1,
  ENTER_ROOM_SUCCESS = 2,
  ENTER_ROOM_ERROR_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ENTER_ROOM_ERROR_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ENTER_ROOM_ERROR_IsValid(int value);
constexpr ENTER_ROOM_ERROR ENTER_ROOM_ERROR_MIN = ENTER_ROOM_NONE;
constexpr ENTER_ROOM_ERROR ENTER_ROOM_ERROR_MAX = ENTER_ROOM_SUCCESS;
constexpr int ENTER_ROOM_ERROR_ARRAYSIZE = ENTER_ROOM_ERROR_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ENTER_ROOM_ERROR_descriptor();
template<typename T>
inline const std::string& ENTER_ROOM_ERROR_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ENTER_ROOM_ERROR>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ENTER_ROOM_ERROR_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ENTER_ROOM_ERROR_descriptor(), enum_t_value);
}
inline bool ENTER_ROOM_ERROR_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ENTER_ROOM_ERROR* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ENTER_ROOM_ERROR>(
    ENTER_ROOM_ERROR_descriptor(), name, value);
}
enum EXIT_ROOM_ERROR : int {
  EXIT_ROOM_NONE = 0,
  EXIT_ROOM_FAIL = 1,
  EXIT_ROOM_SUCCESS = 2,
  EXIT_ROOM_ERROR_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EXIT_ROOM_ERROR_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EXIT_ROOM_ERROR_IsValid(int value);
constexpr EXIT_ROOM_ERROR EXIT_ROOM_ERROR_MIN = EXIT_ROOM_NONE;
constexpr EXIT_ROOM_ERROR EXIT_ROOM_ERROR_MAX = EXIT_ROOM_SUCCESS;
constexpr int EXIT_ROOM_ERROR_ARRAYSIZE = EXIT_ROOM_ERROR_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EXIT_ROOM_ERROR_descriptor();
template<typename T>
inline const std::string& EXIT_ROOM_ERROR_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EXIT_ROOM_ERROR>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EXIT_ROOM_ERROR_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EXIT_ROOM_ERROR_descriptor(), enum_t_value);
}
inline bool EXIT_ROOM_ERROR_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EXIT_ROOM_ERROR* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EXIT_ROOM_ERROR>(
    EXIT_ROOM_ERROR_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::CREATE_PLAYER_ERROR> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::CREATE_PLAYER_ERROR>() {
  return ::Protocol::CREATE_PLAYER_ERROR_descriptor();
}
template <> struct is_proto_enum< ::Protocol::LOGIN_ERROR> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::LOGIN_ERROR>() {
  return ::Protocol::LOGIN_ERROR_descriptor();
}
template <> struct is_proto_enum< ::Protocol::LOGOUT_ERROR> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::LOGOUT_ERROR>() {
  return ::Protocol::LOGOUT_ERROR_descriptor();
}
template <> struct is_proto_enum< ::Protocol::CHAT_ERROR> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::CHAT_ERROR>() {
  return ::Protocol::CHAT_ERROR_descriptor();
}
template <> struct is_proto_enum< ::Protocol::CHAT_STATE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::CHAT_STATE>() {
  return ::Protocol::CHAT_STATE_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ENTER_ROOM_ERROR> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ENTER_ROOM_ERROR>() {
  return ::Protocol::ENTER_ROOM_ERROR_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EXIT_ROOM_ERROR> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EXIT_ROOM_ERROR>() {
  return ::Protocol::EXIT_ROOM_ERROR_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
