// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCp/ChNDUkVBVEVfUExBWUVSX0VSUk9S",
            "EhYKEkNSRUFURV9QTEFZRVJfTk9ORRAAEhYKEkNSRUFURV9QTEFZRVJfRkFJ",
            "TBABEhkKFUNSRUFURV9QTEFZRVJfU1VDQ0VTUxACEh0KGUNSRUFURV9QTEFZ",
            "RVJfRFVQTElDQVRJT04QAypgChNTRUxFQ1RfUExBWUVSX0VSUk9SEhYKElNF",
            "TEVDVF9QTEFZRVJfTk9ORRAAEhYKElNFTEVDVF9QTEFZRVJfRkFJTBABEhkK",
            "FVNFTEVDVF9QTEFZRVJfU1VDQ0VTUxACKlQKEEVOVEVSX0dBTUVfRVJST1IS",
            "EwoPRU5URVJfR0FNRV9OT05FEAASEwoPRU5URVJfR0FNRV9GQUlMEAESFgoS",
            "RU5URVJfR0FNRV9TVUNDRVNTEAIqPAoKTU9WRV9FUlJPUhINCglNT1ZFX05P",
            "TkUQABINCglNT1ZFX0ZBSUwQARIQCgxNT1ZFX1NVQ0NFU1MQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.CREATE_PLAYER_ERROR), typeof(global::Protocol.SELECT_PLAYER_ERROR), typeof(global::Protocol.ENTER_GAME_ERROR), typeof(global::Protocol.MOVE_ERROR), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CREATE_PLAYER_ERROR {
    /// <summary>
    /// 플레이어가 아직 생성되지 않음
    /// </summary>
    [pbr::OriginalName("CREATE_PLAYER_NONE")] CreatePlayerNone = 0,
    /// <summary>
    /// 플레이어 생성 실패
    /// </summary>
    [pbr::OriginalName("CREATE_PLAYER_FAIL")] CreatePlayerFail = 1,
    /// <summary>
    /// 플레이어 생성 성공
    /// </summary>
    [pbr::OriginalName("CREATE_PLAYER_SUCCESS")] CreatePlayerSuccess = 2,
    /// <summary>
    /// 플레이어 이름 중복
    /// </summary>
    [pbr::OriginalName("CREATE_PLAYER_DUPLICATION")] CreatePlayerDuplication = 3,
  }

  public enum SELECT_PLAYER_ERROR {
    /// <summary>
    /// 플레이어 선택 오류가 없음
    /// </summary>
    [pbr::OriginalName("SELECT_PLAYER_NONE")] SelectPlayerNone = 0,
    /// <summary>
    /// 플레이어 선택 실패
    /// </summary>
    [pbr::OriginalName("SELECT_PLAYER_FAIL")] SelectPlayerFail = 1,
    /// <summary>
    /// 플레이어 선택 성공
    /// </summary>
    [pbr::OriginalName("SELECT_PLAYER_SUCCESS")] SelectPlayerSuccess = 2,
  }

  public enum ENTER_GAME_ERROR {
    /// <summary>
    /// 인게임 진입 없음
    /// </summary>
    [pbr::OriginalName("ENTER_GAME_NONE")] EnterGameNone = 0,
    /// <summary>
    /// 인게임 진입 실패
    /// </summary>
    [pbr::OriginalName("ENTER_GAME_FAIL")] EnterGameFail = 1,
    /// <summary>
    /// 인게임 진입 성공
    /// </summary>
    [pbr::OriginalName("ENTER_GAME_SUCCESS")] EnterGameSuccess = 2,
  }

  public enum MOVE_ERROR {
    /// <summary>
    /// 이동 없음
    /// </summary>
    [pbr::OriginalName("MOVE_NONE")] MoveNone = 0,
    /// <summary>
    /// 이동 실패
    /// </summary>
    [pbr::OriginalName("MOVE_FAIL")] MoveFail = 1,
    /// <summary>
    /// 이동 성공
    /// </summary>
    [pbr::OriginalName("MOVE_SUCCESS")] MoveSuccess = 2,
  }

  #endregion

}

#endregion Designer generated code
